version: "3.0"
services:
  app:
    build: .
    volumes:
      - ./app:/app
    networks:
      - andrew-health-project_default
    command: ["php","imitator.php"]
networks:
  andrew-health-project_default:
    external: true